export const cuisineList = [
    "Coffee",
    "Tea",
    "Juices",
    "Smoothies",
    "Milkshakes",
    "Sodas",
    "Energy Drinks",
    "Water",
    "Cocktails",
    "Mocktails",
    "Wine",
    "Beer",
    "Spirits",
    "Craft Beers",
    "Herbal Teas",
    "Iced Drinks",
    "Bubble Tea",
    "Lemonades",
    "Protein Shakes",
    "Cold Brew",
    "Kombucha",
    "Hot Chocolates",
]
